FROM node:gallium-slim as react

WORKDIR /app

COPY package*.json /app

RUN npm install

COPY . /app

RUN npm run build

# stage 2

FROM nginx:stable-alpine

COPY --from=react /app/build /usr/share/nginx/html

EXPOSE 80

# docker build -f <filename>
